In [13]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: C:\Users\bhumi\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

In [45]:
# import required libraries

import pandas as pd
import numpy as np

In [46]:
# load the datatset

df=pd.read_excel(r"C:\Users\bhumi\Downloads\ApexPlanet_DataAnalytics_Dataset.xlsx")
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [47]:
# check shape

print("Rows and columns:",df.shape)

Rows and columns: (1000, 12)

In [48]:
# data information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [49]:
# data columns

df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

In [50]:
# statistical summary

df.describe()

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [51]:
# create data dictionary

data_dictionary=pd.DataFrame({
    "Column_Name":df.columns,
    "Data_Type":df.dtypes.astype(str),
    "Missing_values":df.isnull().sum().values
})
data_dictionary

                 Column_Name Data_Type  Missing_values
Order_ID            Order_ID    object               0
Order_Date        Order_Date    object               0
Customer_ID      Customer_ID    object               0
Customer_Name  Customer_Name    object               0
Age                      Age   float64              20
Gender                Gender    object               0
City                    City    object              13
Product              Product    object               0
Category            Category    object               0
Quantity            Quantity     int64               0
Unit_Price        Unit_Price   float64               0
Total_Sales      Total_Sales   float64               0

In [52]:
# check missing values

df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [53]:
# handling missing values

df['Age']=df['Age'].fillna(df['Age'].median())
df['City']=df['City'].fillna(df['City'].mode()[0])

In [54]:
# verify

df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

In [55]:
# check duplicates

df.duplicated().sum()

np.int64(0)

In [34]:
df['Order_Date'].dtype

dtype('O')

In [56]:
# standardize data

df['Order_Date']=pd.to_datetime(df['Order_Date'])

In [36]:
df['Order_Date'].dtype

dtype('<M8[ns]')

In [57]:
# outliers detection

numeric_cols = df.select_dtypes(
    include=np.number
).columns

numeric_cols

Index(['Age', 'Quantity', 'Unit_Price', 'Total_Sales'], dtype='object')

In [38]:
for col in numeric_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    print(col, ":", len(outliers))

Age : 0
Quantity : 0
Unit_Price : 0
Total_Sales : 19

In [58]:
# feature engineering

df['Order_Month'] = (
    df['Order_Date']
    .dt.month_name()
)

df['Quarter'] = (
    df['Order_Date']
    .dt.quarter
)

df[['Order_Date',
    'Order_Month',
    'Quarter']].head()

  Order_Date Order_Month  Quarter
0 2025-02-25    February        1
1 2025-10-14     October        4
2 2025-05-13         May        2
3 2025-12-02    December        4
4 2025-11-20    November        4

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   datetime64[ns]
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   float64
 5   Gender         1000 non-null   object
 6   City           1000 non-null   object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
 12  Order_Month    1000 non-null   object
 13  Quarter        1000 non-null   int32
dtypes: datetime64[ns](1), float64(3), int32(1), int64(1), object(8)
memory usage: 105.6+ KB

In [42]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
Order_Month      0
Quarter          0
dtype: int64